//! `Media` — a first-class attachment entity (NOT a Post row, unlike WP). Binary
//! bytes live in `BlobStore` (local FS adapter); the DB stores only `blob_key`.
//! Variant metadata (responsive sizes) is generated by an on-demand/build-time
//! image pipeline rather than WP's eager fixed-size generation, so we store the
//! source dimensions + focal point and let the pipeline derive `srcset`.

use time::OffsetDateTime;

use crate::value::ObjectId;

/// The public URL path prefix under which a `Media` original is served
/// (`GET /media/{id}`). This is the SINGLE source of truth for the media-addressing
/// convention, shared by the media-serving route (`ferropress-http`), the serve-layer
/// `data-media-id` → `src` rewrite (`ferropress-serve`), the editor bridge
/// (`ferropress-editor-bridge`), and the admin client — so the in-editor preview and
/// the published page always agree on an image's URL. Change it here and every seam
/// follows.
pub const MEDIA_URL_PREFIX: &str = "/media/";

/// The HTML attribute the pure renderer emits carrying a media reference token (the
/// image ships `src`-less, since the renderer has no DB to resolve a URL). The serve
/// layer rewrites it into a real `src`; naming it here keeps the emitter
/// (`ferropress-render`) and the rewriter (`ferropress-serve`) in lockstep.
pub const MEDIA_ID_ATTR: &str = "data-media-id";

/// The public URL for a media original by its reference token (a `Media.uuid`):
/// `"/media/{token}"`. The inverse is [`media_token_from_url`].
pub fn media_url(token: &str) -> String {
    format!("{MEDIA_URL_PREFIX}{token}")
}

/// Whether `s` is a valid media reference token: a single URL path segment of
/// `[0-9a-fA-F-]` (a `uuid`), non-empty and ≤ 64 chars. Restricting the charset is
/// what makes the token SAFE to interpolate into an HTML attribute / URL — a token
/// can never carry markup or a path separator — so a hand-crafted `block_tree` can't
/// smuggle an XSS payload through the image placeholder, and the serve rewrite / media
/// route can trust anything that passes this.
pub fn is_media_token(s: &str) -> bool {
    !s.is_empty() && s.len() <= 64 && s.bytes().all(|b| b.is_ascii_hexdigit() || b == b'-')
}

/// Recover the media reference token from a [`media_url`], or `None` if `src` is not a
/// well-formed media URL (wrong prefix, or a token failing [`is_media_token`] — e.g. an
/// externally-pasted image URL). The inverse of [`media_url`].
pub fn media_token_from_url(src: &str) -> Option<&str> {
    let token = src.strip_prefix(MEDIA_URL_PREFIX)?;
    is_media_token(token).then_some(token)
}

#[derive(Debug, Clone, PartialEq)]
pub struct Media {
    pub id: Option<ObjectId>,
    pub uuid: String,
    pub slug: String,
    pub filename: String,
    pub mime_type: String,
    pub byte_size: u64,
    pub width: u32,
    pub height: u32,
    /// Required for a11y (first-class, unlike WP's meta key).
    pub alt_text: String,
    pub caption: String,
    pub description: String,
    /// `BlobStore` key for the original bytes — never the bytes themselves.
    pub blob_key: String,
    /// alt + caption + description, the single `@vectorize` source for `search`.
    pub plaintext: String,
    /// Art-direction focal point in 0.0–1.0 image space (modern expectation).
    pub focal_x: f32,
    pub focal_y: f32,
    pub created_at: OffsetDateTime,
    pub meta: serde_json::Value,

    pub uploaded_by: Option<ObjectId>, // -> User
}

#[cfg(test)]
mod tests {
    use super::{MEDIA_URL_PREFIX, is_media_token, media_token_from_url, media_url};

    #[test]
    fn media_url_round_trips_through_token() {
        for token in ["1", "42", "018f3c2a-7b19-7c44-9e0d-2a1f6b8e5d90"] {
            let url = media_url(token);
            assert!(url.starts_with(MEDIA_URL_PREFIX));
            assert_eq!(media_token_from_url(&url), Some(token));
        }
    }

    #[test]
    fn non_media_srcs_yield_none() {
        assert_eq!(media_token_from_url("fp-media:42"), None); // the retired scheme
        assert_eq!(media_token_from_url("https://example.com/cat.png"), None);
        assert_eq!(media_token_from_url("/media/"), None); // no token
        assert_eq!(media_token_from_url("/mediaX/1"), None); // prefix must match exactly
    }

    #[test]
    fn token_charset_is_restricted_to_uuid_shape() {
        assert!(is_media_token("018f3c2a-7b19-7c44-9e0d-2a1f6b8e5d90"));
        assert!(is_media_token("42"));
        assert!(!is_media_token("")); // empty
        assert!(!is_media_token("a/b")); // path separator
        assert!(!is_media_token("\"><script>")); // markup can never be a token
        assert!(!is_media_token(&"a".repeat(65))); // over the length cap
        // A crafted src whose "token" carries markup is rejected outright.
        assert_eq!(media_token_from_url("/media/\"><script>"), None);
    }
}
