//! `Media` — a first-class attachment entity (NOT a Post row, unlike WP). Binary
//! bytes live in `BlobStore` (local FS adapter); the DB stores only `blob_key`.
//! Variant metadata (responsive sizes) is generated by an on-demand/build-time
//! image pipeline rather than WP's eager fixed-size generation, so we store the
//! source dimensions + focal point and let the pipeline derive `srcset`.

use time::OffsetDateTime;

use crate::value::ObjectId;

#[derive(Debug, Clone, PartialEq)]
pub struct Media {
    pub id: Option<ObjectId>,
    pub uuid: String,
    pub slug: String,
    pub filename: String,
    pub mime_type: String,
    pub byte_size: u64,
    pub width: u32,
    pub height: u32,
    /// Required for a11y (first-class, unlike WP's meta key).
    pub alt_text: String,
    pub caption: String,
    pub description: String,
    /// `BlobStore` key for the original bytes — never the bytes themselves.
    pub blob_key: String,
    /// alt + caption + description, the single `@vectorize` source for `search`.
    pub plaintext: String,
    /// Art-direction focal point in 0.0–1.0 image space (modern expectation).
    pub focal_x: f32,
    pub focal_y: f32,
    pub created_at: OffsetDateTime,
    pub meta: serde_json::Value,

    pub uploaded_by: Option<ObjectId>, // -> User
}
