//! `Media` — a first-class attachment entity (NOT a Post row, unlike WP). Binary
//! bytes live in `BlobStore` (local FS adapter); the DB stores only `blob_key`.
//! Variant metadata (responsive sizes) is generated by an on-demand/build-time
//! image pipeline rather than WP's eager fixed-size generation, so we store the
//! source dimensions + focal point and let the pipeline derive `srcset`.

use time::OffsetDateTime;

use crate::value::ObjectId;

/// The public URL path prefix under which a `Media` original is served
/// (`GET /media/{id}`). This is the SINGLE source of truth for the media-addressing
/// convention, shared by the media-serving route (`ferropress-http`), the serve-layer
/// `data-media-id` → `src` rewrite (`ferropress-serve`), the editor bridge
/// (`ferropress-editor-bridge`), and the admin client — so the in-editor preview and
/// the published page always agree on an image's URL. Change it here and every seam
/// follows.
pub const MEDIA_URL_PREFIX: &str = "/media/";

/// The HTML attribute the pure renderer emits carrying a media id (the image ships
/// `src`-less, since the renderer has no DB to resolve a URL). The serve layer
/// rewrites it into a real `src`; naming it here keeps the emitter
/// (`ferropress-render`) and the rewriter (`ferropress-serve`) in lockstep.
pub const MEDIA_ID_ATTR: &str = "data-media-id";

/// The public URL for a media original by id: `"/media/{id}"`. The inverse is
/// [`media_id_from_url`].
pub fn media_url(id: u64) -> String {
    format!("{MEDIA_URL_PREFIX}{id}")
}

/// Recover the media id from a [`media_url`], or `None` if `src` is not one (e.g. an
/// external image URL or a malformed id). The inverse of [`media_url`].
pub fn media_id_from_url(src: &str) -> Option<u64> {
    src.strip_prefix(MEDIA_URL_PREFIX)?.parse().ok()
}

#[derive(Debug, Clone, PartialEq)]
pub struct Media {
    pub id: Option<ObjectId>,
    pub uuid: String,
    pub slug: String,
    pub filename: String,
    pub mime_type: String,
    pub byte_size: u64,
    pub width: u32,
    pub height: u32,
    /// Required for a11y (first-class, unlike WP's meta key).
    pub alt_text: String,
    pub caption: String,
    pub description: String,
    /// `BlobStore` key for the original bytes — never the bytes themselves.
    pub blob_key: String,
    /// alt + caption + description, the single `@vectorize` source for `search`.
    pub plaintext: String,
    /// Art-direction focal point in 0.0–1.0 image space (modern expectation).
    pub focal_x: f32,
    pub focal_y: f32,
    pub created_at: OffsetDateTime,
    pub meta: serde_json::Value,

    pub uploaded_by: Option<ObjectId>, // -> User
}

#[cfg(test)]
mod tests {
    use super::{MEDIA_URL_PREFIX, media_id_from_url, media_url};

    #[test]
    fn media_url_round_trips_through_id() {
        for id in [0u64, 1, 42, u64::MAX] {
            let url = media_url(id);
            assert!(url.starts_with(MEDIA_URL_PREFIX));
            assert_eq!(media_id_from_url(&url), Some(id));
        }
    }

    #[test]
    fn non_media_srcs_yield_none() {
        assert_eq!(media_id_from_url("fp-media:42"), None); // the retired scheme
        assert_eq!(media_id_from_url("https://example.com/cat.png"), None);
        assert_eq!(media_id_from_url("/media/"), None); // no id
        assert_eq!(media_id_from_url("/media/not-a-number"), None);
        assert_eq!(media_id_from_url("/mediaX/1"), None); // prefix must match exactly
    }
}
